name: Publish Website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies (from lockfile)
      working-directory: ./website
      run: yarn install --frozen-lockfile
    - name: Build
      working-directory: ./website
      run: yarn build 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # That's so stupid...
        publish_dir: ./website/build/website
        cname: coopreneurs.org
