name: Publish Website
on:
  push:
    branches: [ master ]
defaults:
  run:
    working-directory: ./website
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies (from lockfile)
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
        cname: coopreneurs.org
